"""
LinkedIn Industry Name → URN Code mapping.
Source: LinkedIn Industry Codes V2 (Microsoft Learn / LinkedIn API).
Used to convert human-readable industry names to numeric URN codes
expected by the Apify LinkedIn Posts Search Scraper actor.
"""

INDUSTRY_TO_URN: dict[str, int] = {
    "Accommodation Services": 2190,
    "Accounting": 47,
    "Administrative and Support Services": 1912,
    "Advertising Services": 80,
    "Agriculture, Construction, Mining Machinery Manufacturing": 901,
    "Air Transportation": 94,
    "Alternative Medicine": 125,
    "Animation and Post-production": 127,
    "Apparel Manufacturing": 598,
    "Architecture and Planning": 50,
    "Armed Forces": 71,
    "Artists and Writers": 38,
    "Audio and Video Equipment Manufacturing": 973,
    "Automation Machinery Manufacturing": 147,
    "Aviation and Aerospace Component Manufacturing": 52,
    "Banking": 41,
    "Bars, Taverns, and Nightclubs": 2217,
    "Beverage Manufacturing": 142,
    "Biotechnology Research": 12,
    "Book and Periodical Publishing": 82,
    "Breweries": 562,
    "Broadcast Media Production and Distribution": 36,
    "Building Construction": 406,
    "Building Equipment Contractors": 453,
    "Business Consulting and Services": 11,
    "Capital Markets": 129,
    "Chemical Manufacturing": 54,
    "Civic and Social Organizations": 90,
    "Civil Engineering": 51,
    "Claims Adjusting, Actuarial Services": 1738,
    "Coal Mining": 341,
    "Collection Agencies": 1938,
    "Commercial and Industrial Machinery Maintenance": 2247,
    "Communications Equipment Manufacturing": 964,
    "Community Development and Urban Planning": 2374,
    "Community Services": 2115,
    "Computer Hardware Manufacturing": 3,
    "Computer Networking Products": 5,
    "Computers and Electronics Manufacturing": 24,
    "Construction": 48,
    "Consumer Services": 91,
    "Dairy Product Manufacturing": 65,
    "Dance Companies": 2135,
    "Data Infrastructure and Analytics": 2458,
    "Data Security Software Products": 3130,
    "Defense and Space Manufacturing": 1,
    "Dentists": 2045,
    "Design Services": 99,
    "Desktop Computing Software Products": 3101,
    "Distilleries": 564,
    "E-Learning Providers": 132,
    "Education": 1999,
    "Electric Lighting Equipment Manufacturing": 998,
    "Electric Power Generation, Transmission and Distribution": 383,
    "Electrical Equipment Manufacturing": 2468,
    "Electronic and Precision Equipment Maintenance": 2240,
    "Embedded Software Products": 3099,
    "Emergency and Relief Services": 2122,
    "Engineering Services": 3242,
    "Entertainment Providers": 28,
    "Environmental Quality Programs": 388,
    "Environmental Services": 86,
    "Events Services": 110,
    "Executive Offices": 76,
    "Executive Search Services": 1923,
    "Fabricated Metal Products": 840,
    "Facilities Services": 122,
    "Family Planning Centers": 2060,
    "Farming": 63,
    "Farming, Ranching, Forestry": 201,
    "Fashion Accessories Manufacturing": 615,
    "Financial Services": 43,
    "Fine Arts Schools": 2025,
    "Fire Protection": 3070,
    "Fisheries": 66,
    "Flight Training": 2020,
    "Food and Beverage Manufacturing": 23,
    "Food and Beverage Services": 34,
    "Footwear Manufacturing": 622,
    "Forestry and Logging": 298,
    "Freight and Package Transportation": 87,
    "Fuel Cell Manufacturing": 3255,
    "Fundraising": 101,
    "Furniture and Home Furnishings Manufacturing": 26,
    "Gambling Facilities and Casinos": 29,
    "Glass, Ceramics and Concrete Manufacturing": 145,
    "Golf Courses and Country Clubs": 2179,
    "Government Administration": 75,
    "Government Relations Services": 148,
    "Graphic Design": 140,
    "Health and Human Services": 2353,
    "Higher Education": 68,
    "Holding Companies": 1905,
    "Home Health Care Services": 2074,
    "Horticulture": 150,
    "Hospitality": 31,
    "Hospitals": 2081,
    "Hospitals and Health Care": 14,
    "Hotels and Motels": 2194,
    "Household Appliance Manufacturing": 1005,
    "Household Services": 2318,
    "Human Resources Services": 137,
    "HVAC and Refrigeration Equipment Manufacturing": 923,
    "IT Services and IT Consulting": 96,
    "IT System Custom Software Development": 3102,
    "IT System Data Services": 3106,
    "IT System Design Services": 1855,
    "IT System Installation and Disposal": 3104,
    "IT System Operations and Maintenance": 3103,
    "IT System Testing and Evaluation": 3107,
    "IT System Training and Support": 3105,
    "Individual and Family Services": 88,
    "Industrial Machinery Manufacturing": 135,
    "Information Services": 84,
    "Insurance": 42,
    "Insurance Agencies and Brokerages": 1737,
    "Insurance Carriers": 1725,
    "International Affairs": 74,
    "International Trade and Development": 141,
    "Internet Marketplace Platforms": 1285,
    "Internet News": 3124,
    "Internet Publishing": 3132,
    "Investment Advice": 1720,
    "Investment Banking": 45,
    "Investment Management": 46,
    "Janitorial Services": 1965,
    "Landscaping Services": 2934,
    "Language Schools": 2029,
    "Laundry and Drycleaning Services": 2272,
    "Law Enforcement": 77,
    "Law Practice": 9,
    "Leasing Non-residential Real Estate": 128,
    "Leasing Residential Real Estate": 1759,
    "Legal Services": 10,
    "Legislative Offices": 72,
    "Libraries": 85,
    "Loan Brokers": 1696,
    "Machinery Manufacturing": 55,
    "Manufacturing": 25,
    "Market Research": 97,
    "Marketing Services": 1862,
    "Meat Products Manufacturing": 521,
    "Media Production": 126,
    "Medical Equipment Manufacturing": 17,
    "Medical Practices": 13,
    "Mental Health Care": 139,
    "Metal Ore Mining": 345,
    "Military and International Affairs": 2391,
    "Mining": 56,
    "Mobile Computing Software Products": 3100,
    "Mobile Food Services": 2214,
    "Mobile Gaming Apps": 3131,
    "Motor Vehicle Manufacturing": 53,
    "Motor Vehicle Parts Manufacturing": 1042,
    "Movies, Videos and Sound": 35,
    "Museums": 2159,
    "Musicians": 115,
    "Nanotechnology Research": 114,
    "Natural Gas Distribution": 397,
    "Natural Gas Extraction": 3096,
    "Newspaper Publishing": 81,
    "Non-profit Organizations": 100,
    "Nonresidential Building Construction": 413,
    "Nuclear Electric Power Generation": 386,
    "Nursing Homes and Residential Care Facilities": 2091,
    "Office Administration": 1916,
    "Office Furniture and Fixtures Manufacturing": 1090,
    "Oil and Gas": 57,
    "Oil Extraction": 3095,
    "Oil, Gas, and Mining": 332,
    "Online Audio and Video Media": 113,
    "Online and Mail-Order Retail": 1445,
    "Operations Consulting": 2401,
    "Optometrists": 2050,
    "Outsourcing and Offshoring Consulting": 123,
    "Packaging and Containers Manufacturing": 146,
    "Paint, Coating, and Adhesive Manufacturing": 722,
    "Paper and Forest Product Manufacturing": 61,
    "Pension Funds": 1745,
    "Performing Arts": 39,
    "Performing Arts and Spectator Sports": 2130,
    "Personal Care Product Manufacturing": 18,
    "Personal Care Services": 2259,
    "Pet Services": 2282,
    "Pharmaceutical Manufacturing": 15,
    "Philanthropic Fundraising Services": 131,
    "Photography": 136,
    "Physical, Occupational and Speech Therapists": 2054,
    "Physicians": 2040,
    "Pipeline Transportation": 1520,
    "Plastics and Rubber Product Manufacturing": 743,
    "Plastics Manufacturing": 117,
    "Political Organizations": 107,
    "Primary and Secondary Education": 67,
    "Primary Metal Manufacturing": 807,
    "Printing Services": 83,
    "Professional Organizations": 1911,
    "Professional Services": 1810,
    "Professional Training and Coaching": 105,
    "Public Health": 2358,
    "Public Policy Offices": 79,
    "Public Relations and Communications Services": 98,
    "Public Safety": 78,
    "Rail Transportation": 1481,
    "Railroad Equipment Manufacturing": 62,
    "Ranching": 64,
    "Ranching and Fisheries": 256,
    "Real Estate": 44,
    "Real Estate and Equipment Rental Services": 1757,
    "Recreational Facilities": 40,
    "Religious Institutions": 89,
    "Renewable Energy Equipment Manufacturing": 3241,
    "Renewable Energy Power Generation": 3240,
    "Repair and Maintenance": 2225,
    "Research Services": 70,
    "Residential Building Construction": 408,
    "Restaurants": 32,
    "Retail": 27,
    "Retail Apparel and Fashion": 19,
    "Retail Art Dealers": 3186,
    "Retail Books and Printed News": 1409,
    "Retail Building Materials and Garden Equipment": 1324,
    "Retail Florists": 1423,
    "Retail Furniture and Home Furnishings": 1309,
    "Retail Gasoline": 1370,
    "Retail Groceries": 22,
    "Retail Health and Personal Care Products": 1359,
    "Retail Luxury Goods and Jewelry": 143,
    "Retail Motor Vehicles": 1292,
    "Retail Musical Instruments": 1407,
    "Retail Office Equipment": 138,
    "Retail Office Supplies and Gifts": 1424,
    "Retail Recyclable Materials and Used Merchandise": 1431,
    "Savings Institutions": 1678,
    "Seafood Product Manufacturing": 528,
    "Security and Investigations": 121,
    "Security Guards and Patrol Services": 1956,
    "Security Systems Services": 1958,
    "Semiconductor Manufacturing": 7,
    "Services for the Elderly and Disabled": 2112,
    "Shipbuilding": 58,
    "Skiing Facilities": 2181,
    "Soap and Cleaning Product Manufacturing": 727,
    "Software Development": 4,
    "Solar Electric Power Generation": 387,
    "Sound Recording": 1623,
    "Space Research and Technology": 3089,
    "Specialty Trade Contractors": 435,
    "Spectator Sports": 33,
    "Sporting Goods Manufacturing": 20,
    "Sports Teams and Clubs": 2142,
    "Staffing and Recruiting": 104,
    "Strategic Management Services": 102,
    "Sugar and Confectionery Product Manufacturing": 495,
    "Technical and Vocational Training": 2018,
    "Technology, Information and Internet": 6,
    "Technology, Information and Media": 1594,
    "Telecommunications": 8,
    "Telecommunications Carriers": 1644,
    "Telephone Call Centers": 1931,
    "Television Broadcasting": 1633,
    "Temporary Help Services": 1925,
    "Textile Manufacturing": 60,
    "Theater Companies": 2133,
    "Think Tanks": 130,
    "Tobacco Manufacturing": 21,
    "Translation and Localization": 108,
    "Transportation Equipment Manufacturing": 1029,
    "Transportation Programs": 3085,
    "Transportation, Logistics, Supply Chain and Storage": 116,
    "Travel Arrangements": 30,
    "Truck Transportation": 92,
    "Trusts and Estates": 1750,
    "Utilities": 59,
    "Utilities Administration": 3086,
    "Vehicle Repair and Maintenance": 2226,
    "Venture Capital and Private Equity Principals": 106,
    "Veterinary Services": 16,
    "Vocational Rehabilitation Services": 2125,
    "Warehousing and Storage": 93,
    "Waste Collection": 1981,
    "Waste Treatment and Disposal": 1986,
    "Water, Waste, Steam, and Air Conditioning Services": 398,
    "Wellness and Fitness Services": 124,
    "Wholesale": 133,
    "Wholesale Alcoholic Beverages": 1267,
    "Wholesale Apparel and Sewing Supplies": 1222,
    "Wholesale Building Materials": 49,
    "Wholesale Chemical and Allied Products": 1257,
    "Wholesale Computer Equipment": 1157,
    "Wholesale Drugs and Sundries": 1221,
    "Wholesale Electronic Markets and Agents and Brokers": 133,
    "Wholesale Food and Beverage": 1231,
    "Wholesale Furniture and Home Furnishings": 1137,
    "Wholesale Hardware, Plumbing, Heating Equipment": 1178,
    "Wholesale Import and Export": 134,
    "Wholesale Luxury Goods and Jewelry": 1208,
    "Wholesale Machinery": 1187,
    "Wholesale Metals and Minerals": 1166,
    "Wholesale Motor Vehicles and Parts": 1128,
    "Wholesale Paper Products": 1212,
    "Wholesale Petroleum and Petroleum Products": 1262,
    "Wholesale Photography Equipment and Supplies": 1153,
    "Wholesale Recyclable Materials": 1206,
    "Wind Electric Power Generation": 2489,
    "Wineries": 2500,
    "Wireless Services": 119,
    "Wood Product Manufacturing": 784,
    "Writing and Editing": 103,
    "Zoos and Botanical Gardens": 2163,
}


def names_to_urns(sector_csv: str) -> str:
    """Convert comma-separated industry names to comma-separated URN codes.

    Names that have no mapping are dropped (they would fail on Apify anyway).
    """
    names = [n.strip() for n in sector_csv.split(",") if n.strip()]
    codes = []
    for name in names:
        code = INDUSTRY_TO_URN.get(name)
        if code is not None:
            codes.append(str(code))
    return ",".join(codes)
